name: Docker Image CI

on:
  push:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: guestbook-go
  REGISTRY: docker.io
  
jobs:

  build:

    runs-on: ubuntu-latest

    if: ${{ (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || (github.event_name == 'push' && contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')) }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push the image
      working-directory: guestbook-go
      run:  |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
      
      
      
